config/routes.rb
Rails.application.routes.draw do
  get 'branches/new'

  devise_for :users
  resources :users

  resources :projects, shallow: true do
    resources :branches
  end

  resources :branches do
    resources :commits
  end

  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id/commits' => 'users#commits', as: :user_commits

  get 'projects/:id/workspace' => 'workspace#show', as: :workspace

  get 'branches/:id/copy' => 'branches#copy_first_step', as: :branch_copy
  post 'branches/:id/copy' => 'branches#copy_process'

  get 'demo/workspace' => 'workspace#demo_show', as: :demo_workspace

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :project, inverse_of: :branches
  has_one :workspace, inverse_of: :branch
  has_and_belongs_to_many :commits, inverse_of: :branch

  has_many :branch_members
  has_many :contributors, through: :branch_members, source: :user

  # after_create :create_initial_commit
  after_create :create_workspace

  def add_initial_commit(user)
    commits << Commit.new(name: "Initial commit", author: user, project: project)
  end

  def last_commit
    self.commits.last
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :preload, only: [:show]

  def new
    @project = Project.find(params[:project_id])
    @branch = Branch.new(project: @project)
  end

  def create
    @project = Project.find(params[:project_id])
    @branch = @project.branches.create(branch_params)
    @branch.add_initial_commit(current_user)
    respond_to do |format|
      if @branch.save
        format.html { redirect_to @project, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def copy_first_step
    @origin_branch = Branch.find(params[:id])
    @project = @origin_branch.project
    @branch = Branch.new
  end

  def copy_process
    @origin_branch = Branch.find(params[:id])
    @project = @origin_branch.project

    @branch = Branch.new(branch_params.merge(project: @project))
    @branch.commit_ids = @origin_branch.commit_ids
    respond_to do |format|
      if @project.branches << @branch
        format.html { redirect_to @project, notice: 'Branch was successfully copied.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :copy_first_step }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def branch_params
    params.require(:branch).permit(:name)
  end

  def preload
    @branch = Branch.find(params[:id])
    @project = @branch.project || Project.find(params[:project_id])
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/views/branches/_branch_list.html.slim
- if branches.any?
  - branches.each do |branch|
    = render "branches/branch", branch: branch

app/views/branches/_copy_form.html.slim
= form_for @branch, url: branch_copy_path(@origin_branch), method: :post do |f|
  - if @branch.errors.any?
    #error_explanation
      h2
        = pluralize(@branch.errors.count, "error")
        |  prohibited this branches from being saved:
      ul
        - @branch.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .actions
    = f.submit

app/views/branches/_form.html.slim
= form_for @branch, url: project_branches_path(@project, @branch), method: :post do |f|
  - if @branch.errors.any?
    #error_explanation
      h2
        = pluralize(@branch.errors.count, "error")
        |  prohibited this branches from being saved:
      ul
        - @branch.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .actions
    = f.submit

app/views/branches/copy_first_step.html.slim
h1
  | Copy Branch
= render 'copy_form'
= link_to 'Back', project_path(@project)

app/views/branches/new.html.slim
h1
  | New Branch
= render 'form'
= link_to 'Back', project_path(@project)

app/views/branches/show.html.slim
= render "branch", branch: @branch
p = link_to "New Branch", new_project_branch_path(@project)
p = link_to "New Branch (Copy this one)", branch_copy_path(@branch)
p = link_to "New Commit", new_branch_commit_path(@branch)