config/routes.rb
Rails.application.routes.draw do
  get 'branches/new'

  devise_for :users
  resources :users

  resources :projects, shallow: true do
    resources :branches
  end

  resources :branches do
    resources :commits
  end

  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id/commits' => 'users#commits', as: :user_commits

  get 'projects/:id/workspace' => 'workspace#show', as: :workspace

  get 'branches/:id/copy' => 'branches#copy_first_step', as: :branch_copy
  post 'branches/:id/copy' => 'branches#copy_process'

  get 'demo/workspace' => 'workspace#demo_show', as: :demo_workspace

end

app/views/partials/_branch.html.slim
.row.branch.grey-links
  .col-md-6
    .list-item
    h4 = link_to branch.name, branch_path(branch)
  .col-md-6
    .commits-list
      = render "partials/commit_list", commits: branch.commits, branch: branch

app/views/partials/_branch_commit_info.html.slim
.row
  .col-md-6
    h4.centered-text = branches_short_info(project)
  .col-md-6
    h4.centered-text = commits_short_info(project)

app/views/partials/_branch_list.html.slim
- if branches.any?
  - branches.each do |branch|
    = render "partials/branch", branch: branch

app/views/partials/_commit.html.slim
.list-item
  h5 = link_to commit.name, branch_commit_path(branch, commit)

app/views/partials/_commit_list.html.slim
- if commits.any?
  - commits.each do |commit|
    = render "partials/commit", commit: commit, branch: branch

app/views/partials/_contributor.html.slim
- members.each do |member|
  .row.grey-links
    .col-md-4.col-xs-4.header-marginated
      | PHOTO
    .col-md-4.col-xs-4
      h4 = link_to member.user.name, user_path(member.user)
    .col-md-4.col-xs-4.header-marginated
      .role = member.role.slug
.row

app/views/partials/_contributor_list.html.slim
- if project.members.any?
  = render 'partials/contributor', members: project.members

app/views/partials/_project_full_info.html.slim
.col-md-12
  .row.project-container.grey-links
    .col-md-6
      .row.headers
        .col-md-12
          .image[style="background: url(#{project.image.thumb.url}) 50% 50% no-repeat"]
            .tint.white-links
              .row.project-name-row
                .col-md-10.col-xs-10#project-name
                  h1 = link_to project.name, project_path(project)
                .col-md-2.col-xs-2.margin-h1-header#private-container
                  - if project.private?
                    .private = t('project.private')
              .row
                .col-md-12.col-xs-12#author-name
                  h3 = link_to project.author.name, user_path(project.author)
              .row
                .col-md-12.col-xs-12#description
                  .description-container
                    h5 = project.description
    .col-md-6.header-info
      .row
        .col-md-6
          span = t('project.your_role')
          span
            h4 = current_user_role(project)
        .col-md-6
          a.bebas-font[href="#" data-behavior="set-role"] = t('project.set_role')
      .row
        - if current_user_is_author(project)
          .col-md-4
            h4 = link_to I18n.t('project.edit'), edit_project_path(project)
          .col-md-4
            h4 = link_to I18n.t('project.delete'), project, method: :delete, data: { confirm: "Are you sure?" }
        .col-md-4
          h4 = link_to I18n.t('project.workspace'), workspace_url(id: project.id)

  .border-line
  .row
    .col-md-6
      h3.header-stylish = t('project.branches_commits')
      = render "partials/branch_commit_info", project: project
      .row
        .col-md-12
          = render "partials/branch_list", branches: project.branches
          .border-line
    .col-md-6
      h3.header-stylish = t('project.contributors')
      = render "partials/contributor_list", project: project
  .row
    .col-md-9
    .col-md-3.grey-links
      h3.header-stylish = t('project.links')
      .row
        - if current_user_is_author(project)
          .col-md-6
            h4 = link_to "Edit Project", edit_project_path(project)
          .col-md-6
            h4 = link_to "Delete Project", project, method: :delete, data: { confirm: "Are you sure?" }
        .col-md-6
          h4 = link_to "Workspace", workspace_url(id: project.id)
        .col-md-6

app/views/partials/_project_short_info.html.slim
.col-md-6
  .row.project-container.grey-links
    .col-md-12
      .row.headers
        .col-md-12
          .row
            .col-md-10
              .project-name
                h1 = link_to project.name, project_path(project)
            .col-md-2.margin-h1-header
              - if project.private?
                .private = t('project.private')
          .author
            h3 = link_to project.author.name, user_path(project.author)
          .description-container
            h5 = project.description
  .border-line
  .row
    .col-md-12
      h3.header-stylish = t('project.branches_commits')
      = render "partials/branch_commit_info", project: project