config/routes.rb
Rails.application.routes.draw do
  get 'branches/new'

  devise_for :users
  resources :users

  resources :projects, shallow: true do
    resources :branches
  end

  resources :branches do
    resources :commits
  end

  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id/commits' => 'users#commits', as: :user_commits

  get 'projects/:id/workspace' => 'workspace#show', as: :workspace

  get 'branches/:id/copy' => 'branches#copy_first_step', as: :branch_copy
  post 'branches/:id/copy' => 'branches#copy_process'

  get 'demo/workspace' => 'workspace#demo_show', as: :demo_workspace

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :members
  has_many :projects, through: :members

  has_many :branch_members
  has_many :branches, through: :branch_members

  has_many :commits, class_name: "Commit", foreign_key: :author_id
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :commits]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def commits
    @commits = @user.commits.between(params['start'], params['end']) if (params['start'] && params['end'])
    respond_to do |format|
      format.json { render json: @commits, :root => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      h2
        = pluralize(@user.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - @user.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .actions
    = f.submit

app/views/users/edit.html.slim
h1
  | Editing User
= render 'form'
= link_to 'Show', @user
|  | 
= link_to 'Back', users_path

app/views/users/index.html.slim
h1
  | Listing Users
table
  thead
    tr
      th
        | Name
      th[colspan="3"]
  tbody
    - @users.each do |user|
      tr
        td
          = user.name
        td
          = link_to 'Show', user
        td
          = link_to 'Edit', edit_user_path(user)
        td
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1
  | New User
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.slim
#user-creds
  h2#user-name = @user.name
  - if @user == current_user
    #edit-profile-buttons
      = link_to "Edit Profile Info", edit_user_registration_path(@user)
#pre-project-list
  span#project-list-header
    h3 Projects
  span#acton-buttons
    - if @user == current_user
      = link_to "New Project", new_project_path
    = link_to 'Back', :back
#calendar[data-user-id = @user.id]
- unless @user.projects.empty?
  div#project-list
    - @user.projects.each do |project|
      = render "partials/project_short_info", project: project
- else
  h5#notice No projects found.
#chart