config/routes.rb
Rails.application.routes.draw do
  get 'branches/new'

  devise_for :users
  resources :users

  resources :projects, shallow: true do
    resources :branches
  end

  resources :branches do
    resources :commits
  end

  get 'welcome/index'

  root 'welcome#index'

  get 'users/:id/commits' => 'users#commits', as: :user_commits

  get 'projects/:id/workspace' => 'workspace#show', as: :workspace

  get 'branches/:id/copy' => 'branches#copy_first_step', as: :branch_copy
  post 'branches/:id/copy' => 'branches#copy_process'

  get 'demo/workspace' => 'workspace#demo_show', as: :demo_workspace

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :members
  has_many :users, through: :members
  has_many :branches, inverse_of: :project
  has_many :commits

  validates_presence_of :name

  mount_uploader :image, ImageUploader
  validates_processing_of :image
  validate :image_size_validation

  scope :not_private, -> (){ where(private: false) }

  def add_author(user)
    members.create(user: user)
    members.first.create_role
  end

  def initialize_environment(user)
    branch = branches.new(name: "Master")
    branch.contributors << user
    branch.add_initial_commit(user)
    branch.save!
  end

  def author
    members.first.user if members.first.role.is_author?
  end

  def commits_count
    branches.inject(0) {|x, v| x + v.commits.count }
  end

  def master_branch
    branches.first
  end

  def last_branch
    # TODO: implement has_many commits in project and belongs_to project in commits
    Commits.where(branch: self.branches).last
  end

  def find_members(user)
    members.with_user(user)
  end

  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :preload_project, only: [:show, :edit, :update, :destroy]
  before_action :check_membership, only: [:show, :edit]

  def index
    @projects = Project.all
  end

  def show
  end

  def edit
  end

  def create
    @project = Project.create(project_params)
    @project.add_author(current_user)
    @project.initialize_environment(current_user)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @project = Project.new
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :private, :image, :remove_image)
  end

  def check_membership
    if @project.private? && current_user.projects.exclude?(@project)
      flash[:error] = "You cannot view this project, because it is private"
      redirect_to :back # halts request cycle
    end
  end

  def preload_project
    @project = Project.find(params[:id])
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  ROLE_UNSET = 'Unset'

  def branches_short_info (project)
    "Branches: " + project.branches.count.inspect
  end

  def commits_short_info (project)
    "Commits: " + project.commits_count.inspect
  end

  def current_user_role (project)
    members_scope = project.find_members(current_user)
    if members_scope.any?
      members_scope.first.role.slug
    else
      ROLE_UNSET
    end
  end

  def current_user_is_author (project)
    project.author == current_user
  end
end

app/views/projects/_form.html.slim
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      h2
        = pluralize(@project.errors.count, "error")
        |  prohibited this user from being saved:
      ul
        - @project.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_field :name
  .field
    = f.label :description
    br
    = f.text_area :description, size: "24x6"
  .field
    = f.label :private
    br
    = f.check_box :private
  .field
    = f.label :image
    br
    = f.file_field :image
    - if f.object.image?
      = image_tag f.object.image.thumb.url
      = f.label :remove_image
      = f.check_box :remove_image
  .actions
    = f.submit

app/views/projects/_project.html.slim
#project-node
  #up-info
    span#name
      h4 = link_to project.name, project_path(project)
    span#role = project.members.first.role.slug
    - if project.private?
      span#private Private
    span#edit-button
      = link_to "Edit Project", edit_project_path(project)
  #mid-info
    span#branches = branches_short_info(project)
    span#commits = commits_short_info(project)
    span#right = link_to "Workspace", workspace_url(id: project.id)
    span#right = link_to "New Branch", new_project_branch_path(project)
    .row
      .col-md-12
        = render "partials/branch_list", branches: project.branches

  #down-info
    #description = project.description
    - if project.members.first.role.is_author?
      #author-buttons
        = link_to "Edit Project", edit_project_path(project)
        = link_to "Delete Project", project, method: :delete, data: { confirm: "Are you sure?" }

app/views/projects/_project_main.html.slim
.col-md-6
  .row.project-container
    .name
      h2 = link_to project.name, project_path(project)
    .author
      h4 = link_to project.author.name, user_path(project.author)
    .genre
      | Genre: Blues

app/views/projects/edit.html.slim
h1
  | Editing Project
= render 'form'
= link_to 'Show', @project
|  | 
= link_to 'Back', users_path

app/views/projects/index.html.slim
- @projects.each do |project|
  = render "project", project: project
br
= link_to 'New Project', new_project_path

app/views/projects/new.html.slim
h1
  | New Project
= render 'form'
= link_to 'Back', projects_path

app/views/projects/show.html.slim
= render "partials/project_full_info", project: @project